services:
  backend: 
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
  redis: 
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  