services:
  backend:
    build: .
    depends_on:
      - redis
      - mongo
    ports:
      - "8080:8080"
    restart: always
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: always