@url = http://localhost:8080
@_todoId = 63b2d05d6ffcd5a405803cd2

### get all todos
GET {{url}}/todos

### create new todo
POST {{url}}/todos
Content-Type: application/json

{
  "title":"todo",
  "description":"this is a description"
}

### getOne todo
Get {{url}}/todos/{{_todoId}}

### update todo
PATCH  {{url}}/todos/{{_todoId}}
Content-Type: application/json

{
  "title":"update title"
}

### remove todo
DELETE {{url}}/todos/{{_todoId}}