@url = http://localhost:8080
@userId = 63b30e08da288b8ad33d8b42
### get all users
GET {{url}}/users

### create new user
POST {{url}}/users
Content-Type: application/json

{
  "name":"james",
  "email":"john@gmail.com",
  "password":"password"
}

### getOne user
Get {{url}}/users/{{userId}}

### update user
PATCH {{url}}/users/{{userId}}
Content-Type: application/json

{
  "password":"test"
}

### remove user
DELETE {{url}}/users/{{userId}}